### ISSUE TITLE
Better README

### ISSUE THREAD

**Issue by lfarah** [rakaramos/OnOffButton#1]
Hey Rafael, it's nice to see other Brazilians in the Swift Open Source world. I loved your customized button and I want to add it in my repo, [Awesome-iOS](https://github.com/vsouza/awesome-ios). Before I do that, I have to ask you to update your `README.md` with a couple of sections:
# About
# Installation
# Implementation

Let me know if you need any help! 😉

**Comment by rakaramos** [comment]
@lfarah sure thing buddy!

**Comment by rakaramos** [comment]
@lfarah please, check the README. Let me know if it's missing anything!

**Comment by lfarah** [comment]
Good job, @rakaramos. The `implementation` would be how the user would use the button, which you covered under `usage`. I'd also change the description to something like this:

> Custom On/Off Animated UIButton, written in Swift 🔶. By Creativedash

What do you think?

**Comment by lfarah** [comment]
Also, is there a way for devs who don't use Storyboards to implement the button and it's variables? 
(ex: `button.lineWidth = 30`)

**Comment by rakaramos** [comment]
👍

**Comment by lfarah** [comment]
Wow, you're fast! This `README.md` is really **Awesome**!
