### ISSUE TITLE
Swift 3

### ISSUE THREAD

**Issue by Alex293** [rakaramos/OnOffButton#11]
Hi will this project be ported to swift 3 soon ?

**Comment by rakaramos** [comment]
hey, I've just updated the repo, please check the README
as for now, I'm not able to deploy it to cocoapods because due to some issues with Xcode 8 :(

**Comment by Alex293** [comment]
Thank you for your quick reaction ! I will try this soon and give you feedback

**Comment by Alex293** [comment]
The branch is not working. The drawing is done outside of the view bounds and far more bigger than expected.

Here i have a onOffButton centered in a new vc. I for the height to 30 and aspect ratio 1:1

<img width="267" alt="screen shot 2016-09-22 at 23 58 46" src="https://cloud.githubusercontent.com/assets/5930273/18767604/87f2a6b4-8120-11e6-9231-543ceb9be882.png">

**Comment by rakaramos** [comment]
@Alex293 sorry for the long delay.
The code should work now.
