### ISSUE TITLE
How to make it Square

### ISSUE THREAD

**Issue by unittesting0** [rakaramos/OnOffButton#12]
Firstly let me congrats you for this awesome work.

I am worried how to make it Square.

Thank you.

**Comment by rakaramos** [comment]
Hi!
Thanks for you kind words.
I would suggest you to play around with `ringLayer` property.

**Comment by unittesting0** [comment]
Rafael, I have tried but not sure which one changes, I have tried to change ".Round" to ".Square" and "kCALineCapRound" to "kCALineCapSquare" but still don't work.

Would you mind to just take a look at the code, not sure but maybe we should change the innerPath values which I don't know how they were set up.

**Comment by unittesting0** [comment]
@rakaramos can you assist me please?

**Comment by rakaramos** [comment]
Yep, `ringLayer` is a `CAShapeLayer`, you'll need to change the `path` property.
`.Round` and `.Square` are just ways of drawing the lines, therefore this is not what you want.
`UIBezierPath` has some convenience initializers for drawing circles (the one I'm using) and rects.
Check https://developer.apple.com/reference/uikit/uibezierpath
