### ISSUE TITLE
CocoaPods

### ISSUE THREAD

**Issue by lfarah** [rakaramos/OnOffButton#3]
I'd be cool to also add Cocoapods support, as mentioned in the `README.md`. I done this implementation myself last month for my library. Just follow [this post](https://guides.cocoapods.org/making/making-a-cocoapod.html) and [this checklist](https://github.com/thellimist/EZPods).

**Comment by rakaramos** [comment]
👍

**Comment by lfarah** [comment]
_CocoaPods_ **and** _Carthage_? Amazing!!!
