### ISSUE TITLE
Clock hands progress

### ISSUE THREAD

**Issue by cannyboy** [rakaramos/OnOffButton#4]
The tick looks a bit like clock hands. 

I remember the old mac wait cursor (now a 'spinning beachball') had an animated clock:
![screen shot 2016-05-03 at 16 45 23](https://cloud.githubusercontent.com/assets/1590436/14989180/8a399730-114e-11e6-9fe5-9915e670e575.png)

Maybe the button could animate the 'clock hands' until they settle on a tick shape.

**Comment by rakaramos** [comment]
Yeah, that sounds interesting, but the goal here was to mimic the CreativeDash animtion.
But feel free to create a PR with this change. I'll love to see it ;)
