### ISSUE TITLE
Checked property is internal

### ISSUE THREAD

**Issue by jdmcd** [rakaramos/OnOffButton#7]
In this file on this line: https://github.com/rakaramos/OnOffButton/blob/master/Sources/OnOffButton.swift#L28

The `Checked` property is marked as internal, which prevents cocoapods packages from accessing the variable because of the way that pods deal with modules. I suggest updating the variable to a `public` access control to allow cocoapods users to change the state of the control. 

Great framework!!

**Comment by rakaramos** [comment]
Oh, sorry! That should be working now, thanks for pointing that out 👍

**Comment by jdmcd** [comment]
No problem! Glad I could help
